### ISSUE TITLE
upgrade 2.19 to >=3.0

### ISSUE THREAD

**Issue by herz0g** [cinovo/cloudconductor-server#109]
Hi,

I have some problems to upgrade an older cloudconductor instance to a newer version.

Steps to reproduce:

1.) Install a clean Cloudconductor v2.19
2.) Stop the Service
3.) Install a newer package (e.g.: Cloudconductor v3.6)
4.) Start the service

Error:

`12:55:36,093 ERROR liquibase  - classpath:liquibase/changelog.xml: classpath:liquibase/changelog.xml::37::psigloch: Change Set classpath:liquibase/changelog.xml::37::psigloch failed.  Error: ERROR: column "uuid" of relation "host" already exists [Failed SQL: ALTER TABLE cloudconductor.host ADD uuid VARCHAR(255)]
liquibase.exception.DatabaseException: ERROR: column "uuid" of relation "host" already exists [Failed SQL: ALTER TABLE cloudconductor.host ADD uuid VARCHAR(255)]`

Are there any workarounds how to upgrade from an existing Cloudconductor v2.19 to a newer one? I want to prevent to configure all files, keys, etc.?

Install log with all steps to reproduce: https://gist.github.com/herz0g/c2b33be1cf6e057de7a1a54e186f30fa

**Comment by marc92w** [comment]
Hi there,

sorry for the late response, I think the problem is that host uuids were introduced separately in both CC2 and 3. Therefore the uuid column can not be created when migrating to version 3 because it already exists in your database.

We may add a precondition for this Change Set in a future version, in the meantime you can try the following workaround (untested, use at your own risk):

- Stop CC2 service
- Backup your CC2 database
- Clear your cloudconductor.host table and delete the uuid column there
- Start CC3 to run liquibase on the modified database

**Comment by MarcelAbuja** [comment]
Hi, 
the migration worked fine when the uuid was deleted cascading. The hosts are getting deleated with the cleaup task.

Will the hosts that have been connected to the 2.19 Server be able to connect the 3.8 Server without updating the CC client ? Whats the recommended update path ?

**Comment by marc92w** [comment]
Hi Marcel, 

since the API has changed from version 2 to 3 you have to update the agents as well. Here is a short overview of the update path:

- Backup your system
- Stop the v2 agent
- Install the latest agent rpm
- Get auth token: Log into CC server and create an auth token via "Users" > "agent" > "Auth Tokens" > "Add auth token" or copy existing token
- Edit agent config "/opt/cloudconductor-agent/cloudconductor-agent.properties", see example file here: 
  https://github.com/cinovo/cloudconductor-agent-redhat/blob/master/package/cloudconductor-agent.properties
- Start the agent and check if it connects to the server

**Comment by MarcelAbuja** [comment]
Hey marc92w,,

we finished the update successfully. the issue can be closed. Herz0g created the ticket for our project in 2020.

Cheers Marcel
